name: CI Build

on:
  push:
    branches: [develop]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.TOKEN_GITHUB }}
    - name: Setup .NET Core 🔧
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies 🔧
      run: dotnet restore
    - name: Build 🔨
      run: dotnet build --configuration Release --no-restore
    - name: Install AWS Tools 🔧
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: Package 📦
      run: dotnet lambda package ./package.zip -pl ./Source/Service
    - name: Upload package ⬆
      uses: actions/upload-artifact@v1
      with:
        name: package
        path: ./package.zip
      
  deploy-to-qa:
    runs-on: ubuntu-latest
    needs: [package]
    steps:
    - name: Download package ⬇
      uses: actions/download-artifact@v1
      with:
        name: package
    - name: AWS Lambda Deploy 🚀
      uses: appleboy/lambda-action@master
      with:
        zip_file: package/package.zip
        function_name: rebuild-stack-AspNetCoreFunction-S20I8J13N0XY
        aws_region: ${{ secrets.QA_REGION }}
        aws_access_key_id: ${{ secrets.QA_SECRET_ID }}
        aws_secret_access_key: ${{ secrets.QA_SECRET_KEY }}
        
  end-to-end-test:
    runs-on: ubuntu-latest
    needs: [deploy-to-qa]
    steps:
      - name: Set up Python 3.7 🐍
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies 🔧
        run: |
          python -m pip install --upgrade pip
          pip install glasswall-aws-product-test-automation
      - name: Run Tests 🧪
        run: s93_test_automation --product "rebuild" --endpoint "${{ secrets.QA_API_ENDPOINT }}" --api_key "${{ secrets.QA_API_KEY }}" 
        
  merge-to-master:
    runs-on: ubuntu-latest
    needs: [end-to-end-test]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master
      - name: Merge to master branch 🔃
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: master
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN_GITHUB}}        
