name: CI Build

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Install AWS Tools
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: package
      run: dotnet lambda package ./package.zip -pl ./Source/Service
  deploy-to-qa:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@master
      - uses: appleboy/lambda-action@master
        name: AWS Lambda Deploy
        with:
          zip_file: package.zip
          function_name: rebuild-stack-AspNetCoreFunction-S20I8J13N0XY
          aws_region: ${{ secrets.QA_REGION }}
          aws_access_key_id: ${{ secrets.QA_SECRET_ID }}
          aws_secret_access_key: ${{ secrets.QA_SECRET_KEY }}
  ##end-to-end-test:
  ##  runs-on: ubuntu-latest
  ##  needs: [deploy-to-qa]
  merge-to-master:
    runs-on: ubuntu-latest
    needs: [deploy-to-qa]
    steps:
      - uses: actions/checkout@master
      - name: Merge to master branch
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: master
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN_MATT}}        
