name: CI/CD Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
  deploy-to-qa:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@master
      - run: zip lambda.zip *
      - uses: appleboy/lambda-action@master
        name: AWS Lambda Deploy
        with:
          zip_file: lambda.zip
          function_name: rebuild-stack-AspNetCoreFunction-S20I8J13N0XY
          aws_region: ${{ secrets.QA_REGION }}
          aws_access_key_id: ${{ secrets.QA_SECRET_ID }}
          aws_secret_access_key: ${{ secrets.QA_SECRET_KEY }}
          aws_session_token: ${{secrets.QA_SESSION_TOKEN }}
  ##end-to-end-test:
  ##  runs-on: ubuntu-latest
  ##  needs: [deploy-to-qa]
 ## deploy-to-prod1:
  ##  runs-on: ubuntu-latest
  ##  steps:
    ##  - uses: actions/checkout@master
   ##   - run: echo "THIS IS A TEST PACKAGE" > file.txt
    ##  - run: zip lambda.zip file.txt
    ##  - uses: stcalica/update-lambda
    ##    with:
     ##     package: lambda.zip
     ##     function-name: TEST-FUNCTION
     ##     AWS_REGION: ${{ secrets.PROD_REGION }}
     ##     AWS_SECRET_ID: ${{ secrets.PROD_SECRET_ID }}
    ##      AWS_SECRET_KEY: ${{ secrets.PROD_SECRET_KEY }}
