name: Deploy

on:
  push:
    branches: [master]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.TOKEN_MATT }}
      - name: Setup .NET Core 🔧
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Install dependencies 🔧
        run: dotnet restore
      - name: Build 🔨
        run: dotnet build --configuration Release --no-restore
      - name: Install AWS Tools 🔧
        run: dotnet tool install -g Amazon.Lambda.Tools
      - name: Package 📦
        run: dotnet lambda package ./package.zip -pl ./Source/Service
      - name: Upload package ⬆
        uses: actions/upload-artifact@v1
        with:
         name: package
         path: ./package.zip
      
  deploy-to-stage:
    runs-on: ubuntu-latest
    needs: [package]
    steps:
      - name: Download package ⬇
        uses: actions/download-artifact@v1
        with:
          name: package
      - name: AWS Lambda Deploy 🚀
        uses: appleboy/lambda-action@master
        with:
          zip_file: package/package.zip
          function_name: rebuild-stack-AspNetCoreFunction-C5H4HWRVTEGD
          aws_region: ${{ secrets.STAGE_REGION }}
          aws_access_key_id: ${{ secrets.STAGE_SECRET_ID }}
          aws_secret_access_key: ${{ secrets.STAGE_SECRET_KEY }}

  end-to-end-test:
    runs-on: ubuntu-latest
    needs: [deploy-to-stage]
    steps:
      - name: Checkout Test Repo 🛎️
        uses: actions/checkout@master
        with:
          repository: filetrust/rebuild-soft-launch-qa-test-automation
          token: ${{ secrets.TOKEN_MATT }}
      - name: Set up Python 3.7 🐍
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies 🔧
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests 🧪
        run: python -m s93_test_automation --product "rebuild" --endpoint "${{ secrets.STAGE_API_ENDPOINT }}" --api_key "${{ secrets.STAGE_API_KEY }}" 

  deploy-to-prod-1:
    runs-on: ubuntu-latest
    needs: [package]
    steps:
      - name: Download package ⬇
        uses: actions/download-artifact@v1
        with:
          name: package
      - name: AWS Lambda Deploy 🚀
        uses: appleboy/lambda-action@master
        with:
          zip_file: package/package.zip
          function_name: rebuild-stack-AspNetCoreFunction-1VS1BG993QOMQ
          aws_region: ${{ secrets.PROD1_REGION }}
          aws_access_key_id: ${{ secrets.PROD1_SECRET_ID }}
          aws_secret_access_key: ${{ secrets.PROD1_SECRET_KEY }}
       
