name: Gated Build

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]  
        
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 
        with:
          submodules: true
          token: ${{ secrets.TOKEN_GITHUB }}
      - name: Setup .NET Core 🔧
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Install dependencies 🔧
        run: dotnet restore
      - name: Build 🔨
        run: dotnet build --configuration Release --no-restore
      - name: Test 🧪
        run: dotnet test --no-restore --verbosity normal
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        working-directory: gh-page
        run: |
          npm install
          npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
